### ISSUE TITLE
[Cog Suggestion]

### ISSUE THREAD

**Issue by Motzumoto** [JDJG-Holding-Team/Connie-Melody-Skye#1]
you should make a cog thats kinda like shazam where it finds the name of a song if you play it in a vc or something
could provide a snippet of a song in a video to also help you find the source too

by my 2 seconds of googling shazam might have an [api](https://www.shazam.com/shazamkit)

**Comment by JDJGInc** [comment]
This is not a music bot not sure how useful this would be.
Sorry.
Feel free to open if you look at the code and find something else to suggest this idea with.

**Comment by Motzumoto** [comment]
It doesnt have to be a music bot to have a system that can identify music. Its a genuinely good idea but i understand.

**Comment by JDJGInc** [comment]
> It doesnt have to be a music bot to have a system that can identify music. Its a genuinely good idea but i understand.

It may make hard in tos to implement this idea.
It's safer to not.
I may use a spotify suggestion thing and possibly have it look for youtube versions.
